const tasks50 = [
    "Go for a walk and sketch or rewrite everything you find along the road",
    "Write a letter in future for yourself",
    "Draw your dinner",
    "Find a poem to which everything in your soul responds, rewrite it by hand and paste it into a notebook",
    "Glue an envelope to the notebook and put everything that you find on the street in today",
    "Find a photo of a stranger and write him a short biography",
    "Draw only red objects throughout the day",
    "Draw a map of the places where you have been that day",
    "Draw a map of the lines of your palm",
    "Circle your footprints with chalk",
    "Record a conversation overheard",
    "Trace how the moon moves in relation to your home",
    "Go to a paint store and collect samples of your favorite colors",
    "Snatch 15 minutes and eat an orange",
    "Write a hokku",
    "Hang upside down for five minutes",
    "Equip a room on the street from everything you find in nature",
    "Read a book in one day",
    "Illustrate the list of products you want to buy",
    "Write a letter to someone you respect",
    "Prepare breakfast / lunch / dinner in one color theme",
    "Fill a whole page of the notebook with small circles, and then color them",
    "Give something that you love",
    "Select an object and draw the side of it that is not visible to you",
    "List all the places in which you happened to live",
    "Describe in detail your favorite room",
    "Make a mini-booklet about shopping list",
    "Remember your favorite children's game and play",
    "Write in your journal with pen, ink, charcoal, wax crayons, markers, etc",
    "Draw some of your favorite clothes",
    "Make a useful item using only paper and tape",
    "Explore in detail a holiday or ritual from another culture",
    "Arrange a temporary art installation. Use only sticky notes and a pen",
    "Draw a map of the places in the city where you like to sit (you can scan it and give it to a friend",
    "Record all the sounds that you hear during the hour",
    "For one day, give up all media. Write down what came of it",
    "Make a pencil mark on six different surfaces",
    "Draw trash",
    "Make your morning collage. (This refers to a collage that is whipped up in the morning to spur creative thinking)",
    "List ten things that matter most to you (people and animals don't count)",
    "List ten things you would like to do every day",
    "Paste your child's photo into the notebook",
    "Make something out of trash",
    "Make a note in the notebook in CAPITAL LETTERS",
    "Gather some flat natural materials (flowers, leaves) and glue in a notebook",
    "Modify the magazine page - cut a hole, spill tea, singe, crumple, etc",
    "Think of a few color combinations that you react to. Write down, sketch, point out where you see them",
    "Describe something secret in the notebook. Cut the paper with the note into several pieces and glue them on the page mixed together",
    "Write down definitions or descriptions of words or objects that interest you. Use encyclopedias and dictionaries",
    "Draw the outline of the subject without looking at the paper"

]

export default tasks50;